# version: '3.8'

services:
  db:
    image: mariadb:${MARIA_DB_VERSION}
    container_name: ${CONTAINER_NAME}_db
    restart: ${RESTART_OPTION}
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    networks:
      default: null

  www:
    image: www_${CONTAINER_NAME}:${TAG}
    container_name: ${CONTAINER_NAME}_www
    restart: ${RESTART_OPTION}
    build:
      context: ./docker
      args:
        PHP_VERSION: ${PHP_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
    ports:
      - ${WWW_PORT}:80
    volumes:
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./${PROJECT_DIR}:/var/www
    depends_on:
      - db
    networks:
      default: null

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_NAME}_phpma
    restart: ${RESTART_OPTION}
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
      UPLOAD_LIMIT: 20M
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      default: null

networks:
  default:
    name: ${NETWORK_NAME}
