# version: '3.8'

services:
  db:
    image: mariadb:${MARIA_DB_VERSION}
    container_name: ${CONTAINER_NAME}_db
    restart: ${RESTART_OPTION}
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    networks:
      default: null

  www:
    image: www_${CONTAINER_NAME}:${TAG}
    pull_policy: build
    container_name: ${CONTAINER_NAME}_www
    restart: ${RESTART_OPTION}
    build:
      context: ./docker
      args:
        PHP_VERSION: ${PHP_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
    ports:
      - ${WWW_PORT}:80
    volumes:
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./${PROJECT_DIR}:/var/www
    depends_on:
      - db
    networks:
      default: null

  adminer:
    image: shyim/adminerevo:latest
    container_name: ${CONTAINER_NAME}_adminer
    restart: ${RESTART_OPTION}
    environment:
      ADMINER_DEFAULT_DRIVER: ${ADMINER_DRIVER}
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_USER: ${DB_USER}
      ADMINER_DEFAULT_PASSWORD: ${DB_PASSWORD}
      ADMINER_DEFAULT_DB: ${DB_NAME}
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      default: null

networks:
  default:
    name: ${NETWORK_NAME}
